package Method.Client;

import Method.Client.clickgui.ClickGui;
import Method.Client.clickgui.component.Frame;
import Method.Client.managers.*;
import Method.Client.modmaker.DuplicateScreen;
import Method.Client.modmaker.LoadAndSave;
import Method.Client.modmaker.MainMaker;
import Method.Client.module.ModuleManager;
import Method.Client.module.Onscreen.OnscreenGUI;
import Method.Client.module.misc.PlayerHistory;
import Method.Client.utils.Creativetabs.*;
import Method.Client.utils.EventsHandler;
import Method.Client.utils.Factory.MethodConfig;
import Method.Client.utils.Screens.Custom.*;
import Method.Client.utils.Screens.Screen;
import Method.Client.utils.Screens.SubGui;
import Method.Client.utils.Utils;
import Method.Client.utils.font.CFont;
import Method.Client.utils.proxy.ClientProxy;
import Method.Client.utils.proxy.IProxy;
import Method.Client.utils.system.WorldDownloader;
import com.google.common.eventbus.EventBus;
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.lwjgl.opengl.Display;

@Mod(modid = Main.MODID,
        name = Main.NAME,
        version = Main.VERSION,
        acceptableRemoteVersions = "*",
        guiFactory = "Method.Client.utils.Factory.MethodGuiFactory"
)

public class Main {
    @SidedProxy(clientSide = "Method.Client.utils.proxy.ClientProxy",
            serverSide = "Method.Client.utils.proxy.ServerProxy")
    public static IProxy proxy;

    public static final String MODID = "method";
    public static final String NAME = "MethodCode";
    public static final String MODCREDITS = "MethodCode";
    public static final String VERSION = "1.0.0";
    public static final String MCVERSION = "1.12.2";
    public static final String MODURL = "https://github.com/danmaster2/MethodClient";
    public static final String MODLOGO = "assets/method/method.png";
    public static  EventBus eventBus;

    @Mod.Instance
    public static Main instance;
    public static SettingsManager setmgr;
    public static EventsHandler Evtmgr;
    public static OnscreenGUI OnscreenGUI;
    public static PlayerActivity PlayerActivity;
    public static AntiPacketGui AntiPacketgui;
    public static XrayGui Xraygui;
    public static MainMaker Maker;
    public static SearchGui Search;
    public static HoleManager holeManager;
    public static SubGui GuiEsp;
    public static ClickGui ClickGui;
    public static OtherPlayerManager PlayerManager;
    public static DuplicateScreen DuplicateScreen;
    public static MethodConfig config;
    public static LoadAndSave blockSaver;
    public static WorldDownloader worldDownloader;
    public static PlayerHistory playerHistory;
    public static Method.Client.module.render.Xray xray;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false; // stops it from complaining about missing mcmod.info
        event.getModMetadata().name = NAME;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().credits = MODCREDITS;
        event.getModMetadata().url = MODURL;
        event.getModMetadata().logoFile = MODLOGO;

        Utils.loadIconsOnFrames();
        eventBus = new EventBus();
        PlayerManager = new OtherPlayerManager();
        DuplicateScreen = new DuplicateScreen();
        new CreativeTabBlocks();
        new CreativeTabItems();
        new CreativeTabBreak();
        new CreativeTabArmor();
        new CreativeTabFun();
        Display.setTitle("Method Client");
        config = new MethodConfig();
        config.preInit(event);


        Minecraft.getMinecraft().gameSettings.guiScale = 2;
        CFont.setupfont();

        MinecraftForge.EVENT_BUS.register(this);
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.init(event);
        // Initialization Repeat Event handlers!
        Evtmgr = new EventsHandler();
        Xraygui = new XrayGui();
        Maker = new MainMaker();
        Search = new SearchGui();
        AntiPacketgui = new AntiPacketGui();
        GuiEsp = new EspSub();
        setmgr = new SettingsManager(); // SettingsManager BEFORE ModuleManager loaded modules
        PlayerActivity = new PlayerActivity();
        new ModuleManager();
        OnscreenGUI = new OnscreenGUI();
        holeManager = new HoleManager();
        ClickGui = new ClickGui();
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        blockSaver = new LoadAndSave();

        Screen.Initalise();
        new FileManager(); // File manager last so it can put things where they need to go!
        MinecraftForge.EVENT_BUS.register(ClickGui);
        MinecraftForge.EVENT_BUS.register(OnscreenGUI);
        MinecraftForge.EVENT_BUS.register(Evtmgr);
        MinecraftForge.EVENT_BUS.register(PlayerActivity);
        MinecraftForge.EVENT_BUS.register(AntiPacketgui);
        MinecraftForge.EVENT_BUS.register(GuiEsp);
        MinecraftForge.EVENT_BUS.register(Xraygui);
        MinecraftForge.EVENT_BUS.register(Maker);


        MinecraftForge.EVENT_BUS.register(playerHistory);
        if (CommandManager.getInstance() == null)
            CommandManager.getInstance();

        ClientProxy.Gl = ModuleManager.getModuleByName("ArmorRender");

        Main.ClickGui.frames.forEach(Frame::updateRefresh);
        worldDownloader = new WorldDownloader();
        Main.eventBus.register(worldDownloader);

        Xraygui.checkfirstrun();
    }
}
