package Method.Client.modmaker.Windows.Blocks.Utils;

import Method.Client.modmaker.BlockObjects;
import Method.Client.modmaker.MainBlockType;
import Method.Client.modmaker.Tabs;
import Method.Client.modmaker.Windows.Block;
import Method.Client.modmaker.Windows.DragableBlock;
import net.minecraft.block.BlockJukebox;

public class BlockInstance extends Block {

    public BlockInstance() {
        super("BlockInstance", MainBlockType.Boolean, Tabs.Utils, BlockObjects.Name, BlockObjects.NumericalTextEnter, BlockObjects.DropDown);
        this.typesAccepted.add(typesCollapse(MainBlockType.Blocks));
        this.description = "Returns true if input Block is Instanceof Block " + "\n" + "Block instanceof Block";

        ddOptions.add("Block");
        ddOptions.add("BlockAir");
        ddOptions.add("BlockAnvil");
        ddOptions.add("BlockBanner");
        ddOptions.add("BlockBarrier");
        ddOptions.add("BlockBasePressurePlate");
        ddOptions.add("BlockBeacon");
        ddOptions.add("BlockBed");
        ddOptions.add("BlockBeetroot");
        ddOptions.add("BlockBone");
        ddOptions.add("BlockBookshelf");
        ddOptions.add("BlockBreakable");
        ddOptions.add("BlockBrewingStand");
        ddOptions.add("BlockBush");
        ddOptions.add("BlockButton");
        ddOptions.add("BlockButtonStone");
        ddOptions.add("BlockButtonWood");
        ddOptions.add("BlockCactus");
        ddOptions.add("BlockCake");
        ddOptions.add("BlockCarpet");
        ddOptions.add("BlockCarrot");
        ddOptions.add("BlockCauldron");
        ddOptions.add("BlockChest");
        ddOptions.add("BlockChorusFlower");
        ddOptions.add("BlockChorusPlant");
        ddOptions.add("BlockClay");
        ddOptions.add("BlockCocoa");
        ddOptions.add("BlockColored");
        ddOptions.add("BlockCommandBlock");
        ddOptions.add("BlockCompressedPowered");
        ddOptions.add("BlockConcretePowder");
        ddOptions.add("BlockContainer");
        ddOptions.add("BlockCrops");
        ddOptions.add("BlockDaylightDetector");
        ddOptions.add("BlockDeadBush");
        ddOptions.add("BlockDirectional");
        ddOptions.add("BlockDirt");
        ddOptions.add("BlockDispenser");
        ddOptions.add("BlockDoor");
        ddOptions.add("BlockDoublePlant");
        ddOptions.add("BlockDoubleStoneSlab");
        ddOptions.add("BlockDoubleStoneSlabNew");
        ddOptions.add("BlockDoubleWoodSlab");
        ddOptions.add("BlockDragonEgg");
        ddOptions.add("BlockDropper");
        ddOptions.add("BlockDynamicLiquid");
        ddOptions.add("BlockEmptyDrops");
        ddOptions.add("BlockEnchantmentTable");
        ddOptions.add("BlockEnderChest");
        ddOptions.add("BlockEndGateway");
        ddOptions.add("BlockEndPortal");
        ddOptions.add("BlockEndPortalFrame");
        ddOptions.add("BlockEndRod");
        ddOptions.add("BlockEventData");
        ddOptions.add("BlockFalling");
        ddOptions.add("BlockFarmland");
        ddOptions.add("BlockFence");
        ddOptions.add("BlockFenceGate");
        ddOptions.add("BlockFire");
        ddOptions.add("BlockFlower");
        ddOptions.add("BlockFlowerPot");
        ddOptions.add("BlockFrostedIce");
        ddOptions.add("BlockFurnace");
        ddOptions.add("BlockGlass");
        ddOptions.add("BlockGlazedTerracotta");
        ddOptions.add("BlockGlowstone");
        ddOptions.add("BlockGrass");
        ddOptions.add("BlockGrassPath");
        ddOptions.add("BlockGravel");
        ddOptions.add("BlockHalfStoneSlab");
        ddOptions.add("BlockHalfStoneSlabNew");
        ddOptions.add("BlockHalfWoodSlab");
        ddOptions.add("BlockHardenedClay");
        ddOptions.add("BlockHay");
        ddOptions.add("BlockHopper");
        ddOptions.add("BlockHorizontal");
        ddOptions.add("BlockHugeMushroom");
        ddOptions.add("BlockIce");
        ddOptions.add("BlockJukebox");
        ddOptions.add("BlockLadder");
        ddOptions.add("BlockLeaves");
        ddOptions.add("BlockLever");
        ddOptions.add("BlockLilyPad");
        ddOptions.add("BlockLiquid");
        ddOptions.add("BlockLog");
        ddOptions.add("BlockMagma");
        ddOptions.add("BlockMelon");
        ddOptions.add("BlockMobSpawner");
        ddOptions.add("BlockMushroom");
        ddOptions.add("BlockMycelium");
        ddOptions.add("BlockNetherBrick");
        ddOptions.add("BlockNetherrack");
        ddOptions.add("BlockNetherWart");
        ddOptions.add("BlockNewLeaf");
        ddOptions.add("BlockNewLog");
        ddOptions.add("BlockNote");
        ddOptions.add("BlockObserver");
        ddOptions.add("BlockObsidian");
        ddOptions.add("BlockOldLeaf");
        ddOptions.add("BlockOldLog");
        ddOptions.add("BlockOre");
        ddOptions.add("BlockPackedIce");
        ddOptions.add("BlockPane");
        ddOptions.add("BlockPistonBase");
        ddOptions.add("BlockPistonExtension");
        ddOptions.add("BlockPistonMoving");
        ddOptions.add("BlockPlanks");
        ddOptions.add("BlockPortal");
        ddOptions.add("BlockPotato");
        ddOptions.add("BlockPressurePlate");
        ddOptions.add("BlockPressurePlateWeighted");
        ddOptions.add("BlockPrismarine");
        ddOptions.add("BlockPumpkin");
        ddOptions.add("BlockPurpurSlab");
        ddOptions.add("BlockQuartz");
        ddOptions.add("BlockRail");
        ddOptions.add("BlockRailBase");
        ddOptions.add("BlockRailDetector");
        ddOptions.add("BlockRailPowered");
        ddOptions.add("BlockRedFlower");
        ddOptions.add("BlockRedSandstone");
        ddOptions.add("BlockRedstoneComparator");
        ddOptions.add("BlockRedstoneDiode");
        ddOptions.add("BlockRedstoneLight");
        ddOptions.add("BlockRedstoneOre");
        ddOptions.add("BlockRedstoneRepeater");
        ddOptions.add("BlockRedstoneTorch");
        ddOptions.add("BlockRedstoneWire");
        ddOptions.add("BlockReed");
        ddOptions.add("BlockRotatedPillar");
        ddOptions.add("BlockSand");
        ddOptions.add("BlockSandStone");
        ddOptions.add("BlockSapling");
        ddOptions.add("BlockSeaLantern");
        ddOptions.add("BlockShulkerBox");
        ddOptions.add("BlockSign");
        ddOptions.add("BlockSilverfish");
        ddOptions.add("BlockSkull");
        ddOptions.add("BlockSlab");
        ddOptions.add("BlockSlime");
        ddOptions.add("BlockSnow");
        ddOptions.add("BlockSnowBlock");
        ddOptions.add("BlockSoulSand");
        ddOptions.add("BlockSourceImpl");
        ddOptions.add("BlockSponge");
        ddOptions.add("BlockStainedGlass");
        ddOptions.add("BlockStainedGlassPane");
        ddOptions.add("BlockStainedHardenedClay");
        ddOptions.add("BlockStairs");
        ddOptions.add("BlockStandingSign");
        ddOptions.add("BlockStaticLiquid");
        ddOptions.add("BlockStem");
        ddOptions.add("BlockStone");
        ddOptions.add("BlockStoneBrick");
        ddOptions.add("BlockStoneSlab");
        ddOptions.add("BlockStoneSlabNew");
        ddOptions.add("BlockStructure");
        ddOptions.add("BlockStructureVoid");
        ddOptions.add("BlockTallGrass");
        ddOptions.add("BlockTNT");
        ddOptions.add("BlockTorch");
        ddOptions.add("BlockTrapDoor");
        ddOptions.add("BlockTripWire");
        ddOptions.add("BlockTripWireHook");
        ddOptions.add("BlockVine");
        ddOptions.add("BlockWall");
        ddOptions.add("BlockWallSign");
        ddOptions.add("BlockWeb");
        ddOptions.add("BlockWoodSlab");
        ddOptions.add("BlockWorkbench");
        ddOptions.add("BlockYellowFlower");

    }

    @Override
    public boolean runCodeBoolean(DragableBlock dragableBlock, Object event) {
        switch (dragableBlock.dropDowns.getSelected()) {
            case "Block": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.Block;
            case "BlockAir": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockAir;
            case "BlockAnvil": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockAnvil;
            case "BlockBanner": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBanner;
            case "BlockBarrier": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBarrier;
            case "BlockBasePressurePlate": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBasePressurePlate;
            case "BlockBeacon": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBeacon;
            case "BlockBed": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBed;
            case "BlockBeetroot": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBeetroot;
            case "BlockBone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBone;
            case "BlockBookshelf": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBookshelf;
            case "BlockBreakable": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBreakable;
            case "BlockBrewingStand": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBrewingStand;
            case "BlockBush": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockBush;
            case "BlockButton": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockButton;
            case "BlockButtonStone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockButtonStone;
            case "BlockButtonWood": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockButtonWood;
            case "BlockCactus": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCactus;
            case "BlockCake": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCake;
            case "BlockCarpet": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCarpet;
            case "BlockCarrot": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCarrot;
            case "BlockCauldron": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCauldron;
            case "BlockChest": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockChest;
            case "BlockChorusFlower": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockChorusFlower;
            case "BlockChorusPlant": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockChorusPlant;
            case "BlockClay": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockClay;
            case "BlockCocoa": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCocoa;
            case "BlockColored": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockColored;
            case "BlockCommandBlock": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCommandBlock;
            case "BlockCompressedPowered": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCompressedPowered;
            case "BlockConcretePowder": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockConcretePowder;
            case "BlockContainer": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockContainer;
            case "BlockCrops": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockCrops;
            case "BlockDaylightDetector": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDaylightDetector;
            case "BlockDeadBush": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDeadBush;
            case "BlockDirectional": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDirectional;
            case "BlockDirt": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDirt;
            case "BlockDispenser": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDispenser;
            case "BlockDoor": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDoor;
            case "BlockDoublePlant": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDoublePlant;
            case "BlockDoubleStoneSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDoubleStoneSlab;
            case "BlockDoubleStoneSlabNew": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDoubleStoneSlabNew;
            case "BlockDoubleWoodSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDoubleWoodSlab;
            case "BlockDragonEgg": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDragonEgg;
            case "BlockDropper": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDropper;
            case "BlockDynamicLiquid": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockDynamicLiquid;
            case "BlockEmptyDrops": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEmptyDrops;
            case "BlockEnchantmentTable": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEnchantmentTable;
            case "BlockEnderChest": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEnderChest;
            case "BlockEndGateway": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEndGateway;
            case "BlockEndPortal": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEndPortal;
            case "BlockEndPortalFrame": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEndPortalFrame;
            case "BlockEndRod": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEndRod;
            case "BlockEventData": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockEventData;
            case "BlockFalling": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFalling;
            case "BlockFarmland": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFarmland;
            case "BlockFence": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFence;
            case "BlockFenceGate": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFenceGate;
            case "BlockFire": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFire;
            case "BlockFlower": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFlower;
            case "BlockFlowerPot": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFlowerPot;
            case "BlockFrostedIce": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFrostedIce;
            case "BlockFurnace": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockFurnace;
            case "BlockGlass": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGlass;
            case "BlockGlazedTerracotta": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGlazedTerracotta;
            case "BlockGlowstone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGlowstone;
            case "BlockGrass": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGrass;
            case "BlockGrassPath": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGrassPath;
            case "BlockGravel": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockGravel;
            case "BlockHalfStoneSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHalfStoneSlab;
            case "BlockHalfStoneSlabNew": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHalfStoneSlabNew;
            case "BlockHalfWoodSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHalfWoodSlab;
            case "BlockHardenedClay": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHardenedClay;
            case "BlockHay": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHay;
            case "BlockHopper": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHopper;
            case "BlockHorizontal": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHorizontal;
            case "BlockHugeMushroom": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockHugeMushroom;
            case "BlockIce": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockIce;
            case "BlockJukebox": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof BlockJukebox;
            case "BlockLadder": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLadder;
            case "BlockLeaves": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLeaves;
            case "BlockLever": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLever;
            case "BlockLilyPad": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLilyPad;
            case "BlockLiquid": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLiquid;
            case "BlockLog": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockLog;
            case "BlockMagma": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockMagma;
            case "BlockMelon": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockMelon;
            case "BlockMobSpawner": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockMobSpawner;
            case "BlockMushroom": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockMushroom;
            case "BlockMycelium": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockMycelium;
            case "BlockNetherBrick": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNetherBrick;
            case "BlockNetherrack": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNetherrack;
            case "BlockNetherWart": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNetherWart;
            case "BlockNewLeaf": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNewLeaf;
            case "BlockNewLog": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNewLog;
            case "BlockNote": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockNote;
            case "BlockObserver": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockObserver;
            case "BlockObsidian": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockObsidian;
            case "BlockOldLeaf": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockOldLeaf;
            case "BlockOldLog": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockOldLog;
            case "BlockOre": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockOre;
            case "BlockPackedIce": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPackedIce;
            case "BlockPane": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPane;
            case "BlockPistonBase": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPistonBase;
            case "BlockPistonExtension": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPistonExtension;
            case "BlockPistonMoving": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPistonMoving;
            case "BlockPlanks": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPlanks;
            case "BlockPortal": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPortal;
            case "BlockPotato": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPotato;
            case "BlockPressurePlate": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPressurePlate;
            case "BlockPressurePlateWeighted": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPressurePlateWeighted;
            case "BlockPrismarine": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPrismarine;
            case "BlockPumpkin": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPumpkin;
            case "BlockPurpurSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockPurpurSlab;
            case "BlockQuartz": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockQuartz;
            case "BlockRail": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRail;
            case "BlockRailBase": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRailBase;
            case "BlockRailDetector": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRailDetector;
            case "BlockRailPowered": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRailPowered;
            case "BlockRedFlower": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedFlower;
            case "BlockRedSandstone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedSandstone;
            case "BlockRedstoneComparator": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneComparator;
            case "BlockRedstoneDiode": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneDiode;
            case "BlockRedstoneLight": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneLight;
            case "BlockRedstoneOre": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneOre;
            case "BlockRedstoneRepeater": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneRepeater;
            case "BlockRedstoneTorch": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneTorch;
            case "BlockRedstoneWire": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRedstoneWire;
            case "BlockReed": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockReed;
            case "BlockRotatedPillar": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockRotatedPillar;
            case "BlockSand": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSand;
            case "BlockSandStone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSandStone;
            case "BlockSapling": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSapling;
            case "BlockSeaLantern": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSeaLantern;
            case "BlockShulkerBox": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockShulkerBox;
            case "BlockSign": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSign;
            case "BlockSilverfish": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSilverfish;
            case "BlockSkull": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSkull;
            case "BlockSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSlab;
            case "BlockSlime": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSlime;
            case "BlockSnow": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSnow;
            case "BlockSnowBlock": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSnowBlock;
            case "BlockSoulSand": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSoulSand;
            case "BlockSourceImpl": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSourceImpl;
            case "BlockSponge": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockSponge;
            case "BlockStainedGlass": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStainedGlass;
            case "BlockStainedGlassPane": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStainedGlassPane;
            case "BlockStainedHardenedClay": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStainedHardenedClay;
            case "BlockStairs": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStairs;
            case "BlockStandingSign": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStandingSign;
            case "BlockStaticLiquid": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStaticLiquid;
            case "BlockStem": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStem;
            case "BlockStone": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStone;
            case "BlockStoneBrick": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStoneBrick;
            case "BlockStoneSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStoneSlab;
            case "BlockStoneSlabNew": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStoneSlabNew;
            case "BlockStructure": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStructure;
            case "BlockStructureVoid": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockStructureVoid;
            case "BlockTallGrass": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTallGrass;
            case "BlockTNT": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTNT;
            case "BlockTorch": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTorch;
            case "BlockTrapDoor": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTrapDoor;
            case "BlockTripWire": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTripWire;
            case "BlockTripWireHook": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockTripWireHook;
            case "BlockVine": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockVine;
            case "BlockWall": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockWall;
            case "BlockWallSign": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockWallSign;
            case "BlockWeb": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockWeb;
            case "BlockWoodSlab": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockWoodSlab;
            case "BlockWorkbench": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockWorkbench;
            case "BlockYellowFlower": return dragableBlock.local.codeExecuter.solveObject(dragableBlock,0, event) instanceof net.minecraft.block.BlockYellowFlower;



        }
        return false;

    }

}
