package Method.Client.modmaker.Windows.Blocks.Utils;

import Method.Client.modmaker.BlockObjects;
import Method.Client.modmaker.MainBlockType;
import Method.Client.modmaker.Tabs;
import Method.Client.modmaker.Windows.Block;
import Method.Client.modmaker.Windows.DragableBlock;
import net.minecraft.init.Blocks;

public class ReturnBlock extends Block {

    public ReturnBlock() {
        super("ReturnBlock", MainBlockType.Blocks, Tabs.Utils, BlockObjects.Name,BlockObjects.DropDown);

        this.description = "Returns the block class of the block";

        ddOptions.add("AIR");
        ddOptions.add("STONE");
        ddOptions.add("GRASS");
        ddOptions.add("DIRT");
        ddOptions.add("COBBLESTONE");
        ddOptions.add("PLANKS");
        ddOptions.add("SAPLING");
        ddOptions.add("BEDROCK");
        ddOptions.add("FLOWING_WATER");
        ddOptions.add("WATER");
        ddOptions.add("FLOWING_LAVA");
        ddOptions.add("LAVA");
        ddOptions.add("SAND");
        ddOptions.add("GRAVEL");
        ddOptions.add("GOLD_ORE");
        ddOptions.add("IRON_ORE");
        ddOptions.add("COAL_ORE");
        ddOptions.add("LOG");
        ddOptions.add("LOG2");
        ddOptions.add("LEAVES");
        ddOptions.add("LEAVES2");
        ddOptions.add("SPONGE");
        ddOptions.add("GLASS");
        ddOptions.add("LAPIS_ORE");
        ddOptions.add("LAPIS_BLOCK");
        ddOptions.add("DISPENSER");
        ddOptions.add("SANDSTONE");
        ddOptions.add("NOTEBLOCK");
        ddOptions.add("BED");
        ddOptions.add("GOLDEN_RAIL");
        ddOptions.add("DETECTOR_RAIL");
        ddOptions.add("STICKY_PISTON");
        ddOptions.add("WEB");
        ddOptions.add("TALLGRASS");
        ddOptions.add("DEADBUSH");
        ddOptions.add("PISTON");
        ddOptions.add("PISTON_HEAD");
        ddOptions.add("WOOL");
        ddOptions.add("PISTON_EXTENSION");
        ddOptions.add("YELLOW_FLOWER");
        ddOptions.add("RED_FLOWER");
        ddOptions.add("BROWN_MUSHROOM");
        ddOptions.add("RED_MUSHROOM");
        ddOptions.add("GOLD_BLOCK");
        ddOptions.add("IRON_BLOCK");
        ddOptions.add("DOUBLE_STONE_SLAB");
        ddOptions.add("STONE_SLAB");
        ddOptions.add("BRICK_BLOCK");
        ddOptions.add("TNT");
        ddOptions.add("BOOKSHELF");
        ddOptions.add("MOSSY_COBBLESTONE");
        ddOptions.add("OBSIDIAN");
        ddOptions.add("TORCH");
        ddOptions.add("FIRE");
        ddOptions.add("MOB_SPAWNER");
        ddOptions.add("OAK_STAIRS");
        ddOptions.add("CHEST");
        ddOptions.add("REDSTONE_WIRE");
        ddOptions.add("DIAMOND_ORE");
        ddOptions.add("DIAMOND_BLOCK");
        ddOptions.add("CRAFTING_TABLE");
        ddOptions.add("WHEAT");
        ddOptions.add("FARMLAND");
        ddOptions.add("FURNACE");
        ddOptions.add("LIT_FURNACE");
        ddOptions.add("STANDING_SIGN");
        ddOptions.add("OAK_DOOR");
        ddOptions.add("SPRUCE_DOOR");
        ddOptions.add("BIRCH_DOOR");
        ddOptions.add("JUNGLE_DOOR");
        ddOptions.add("ACACIA_DOOR");
        ddOptions.add("DARK_OAK_DOOR");
        ddOptions.add("LADDER");
        ddOptions.add("RAIL");
        ddOptions.add("STONE_STAIRS");
        ddOptions.add("WALL_SIGN");
        ddOptions.add("LEVER");
        ddOptions.add("STONE_PRESSURE_PLATE");
        ddOptions.add("IRON_DOOR");
        ddOptions.add("WOODEN_PRESSURE_PLATE");
        ddOptions.add("REDSTONE_ORE");
        ddOptions.add("LIT_REDSTONE_ORE");
        ddOptions.add("UNLIT_REDSTONE_TORCH");
        ddOptions.add("REDSTONE_TORCH");
        ddOptions.add("STONE_BUTTON");
        ddOptions.add("SNOW_LAYER");
        ddOptions.add("ICE");
        ddOptions.add("SNOW");
        ddOptions.add("CACTUS");
        ddOptions.add("CLAY");
        ddOptions.add("REEDS");
        ddOptions.add("JUKEBOX");
        ddOptions.add("OAK_FENCE");
        ddOptions.add("SPRUCE_FENCE");
        ddOptions.add("BIRCH_FENCE");
        ddOptions.add("JUNGLE_FENCE");
        ddOptions.add("DARK_OAK_FENCE");
        ddOptions.add("ACACIA_FENCE");
        ddOptions.add("PUMPKIN");
        ddOptions.add("NETHERRACK");
        ddOptions.add("SOUL_SAND");
        ddOptions.add("GLOWSTONE");
        ddOptions.add("PORTAL");
        ddOptions.add("LIT_PUMPKIN");
        ddOptions.add("CAKE");
        ddOptions.add("UNPOWERED_REPEATER");
        ddOptions.add("POWERED_REPEATER");
        ddOptions.add("TRAPDOOR");
        ddOptions.add("MONSTER_EGG");
        ddOptions.add("STONEBRICK");
        ddOptions.add("BROWN_MUSHROOM_BLOCK");
        ddOptions.add("RED_MUSHROOM_BLOCK");
        ddOptions.add("IRON_BARS");
        ddOptions.add("GLASS_PANE");
        ddOptions.add("MELON_BLOCK");
        ddOptions.add("PUMPKIN_STEM");
        ddOptions.add("MELON_STEM");
        ddOptions.add("VINE");
        ddOptions.add("OAK_FENCE_GATE");
        ddOptions.add("SPRUCE_FENCE_GATE");
        ddOptions.add("BIRCH_FENCE_GATE");
        ddOptions.add("JUNGLE_FENCE_GATE");
        ddOptions.add("DARK_OAK_FENCE_GATE");
        ddOptions.add("ACACIA_FENCE_GATE");
        ddOptions.add("BRICK_STAIRS");
        ddOptions.add("STONE_BRICK_STAIRS");
        ddOptions.add("MYCELIUM");
        ddOptions.add("WATERLILY");
        ddOptions.add("NETHER_BRICK");
        ddOptions.add("NETHER_BRICK_FENCE");
        ddOptions.add("NETHER_BRICK_STAIRS");
        ddOptions.add("NETHER_WART");
        ddOptions.add("ENCHANTING_TABLE");
        ddOptions.add("BREWING_STAND");
        ddOptions.add("CAULDRON");
        ddOptions.add("END_PORTAL");
        ddOptions.add("END_PORTAL_FRAME");
        ddOptions.add("END_STONE");
        ddOptions.add("DRAGON_EGG");
        ddOptions.add("REDSTONE_LAMP");
        ddOptions.add("LIT_REDSTONE_LAMP");
        ddOptions.add("DOUBLE_WOODEN_SLAB");
        ddOptions.add("WOODEN_SLAB");
        ddOptions.add("COCOA");
        ddOptions.add("SANDSTONE_STAIRS");
        ddOptions.add("EMERALD_ORE");
        ddOptions.add("ENDER_CHEST");
        ddOptions.add("TRIPWIRE_HOOK");
        ddOptions.add("TRIPWIRE");
        ddOptions.add("EMERALD_BLOCK");
        ddOptions.add("SPRUCE_STAIRS");
        ddOptions.add("BIRCH_STAIRS");
        ddOptions.add("JUNGLE_STAIRS");
        ddOptions.add("COMMAND_BLOCK");
        ddOptions.add("BEACON");
        ddOptions.add("COBBLESTONE_WALL");
        ddOptions.add("FLOWER_POT");
        ddOptions.add("CARROTS");
        ddOptions.add("POTATOES");
        ddOptions.add("WOODEN_BUTTON");
        ddOptions.add("SKULL");
        ddOptions.add("ANVIL");
        ddOptions.add("TRAPPED_CHEST");
        ddOptions.add("LIGHT_WEIGHTED_PRESSURE_PLATE");
        ddOptions.add("HEAVY_WEIGHTED_PRESSURE_PLATE");
        ddOptions.add("UNPOWERED_COMPARATOR");
        ddOptions.add("POWERED_COMPARATOR");
        ddOptions.add("DAYLIGHT_DETECTOR");
        ddOptions.add("DAYLIGHT_DETECTOR_INVERTED");
        ddOptions.add("REDSTONE_BLOCK");
        ddOptions.add("QUARTZ_ORE");
        ddOptions.add("HOPPER");
        ddOptions.add("QUARTZ_BLOCK");
        ddOptions.add("QUARTZ_STAIRS");
        ddOptions.add("ACTIVATOR_RAIL");
        ddOptions.add("DROPPER");
        ddOptions.add("STAINED_HARDENED_CLAY");
        ddOptions.add("BARRIER");
        ddOptions.add("IRON_TRAPDOOR");
        ddOptions.add("HAY_BLOCK");
        ddOptions.add("CARPET");
        ddOptions.add("HARDENED_CLAY");
        ddOptions.add("COAL_BLOCK");
        ddOptions.add("PACKED_ICE");
        ddOptions.add("ACACIA_STAIRS");
        ddOptions.add("DARK_OAK_STAIRS");
        ddOptions.add("SLIME_BLOCK");
        ddOptions.add("DOUBLE_PLANT");
        ddOptions.add("STAINED_GLASS");
        ddOptions.add("STAINED_GLASS_PANE");
        ddOptions.add("PRISMARINE");
        ddOptions.add("SEA_LANTERN");
        ddOptions.add("STANDING_BANNER");
        ddOptions.add("WALL_BANNER");
        ddOptions.add("RED_SANDSTONE");
        ddOptions.add("RED_SANDSTONE_STAIRS");
        ddOptions.add("DOUBLE_STONE_SLAB2");
        ddOptions.add("STONE_SLAB2");
        ddOptions.add("END_ROD");
        ddOptions.add("CHORUS_PLANT");
        ddOptions.add("CHORUS_FLOWER");
        ddOptions.add("PURPUR_BLOCK");
        ddOptions.add("PURPUR_PILLAR");
        ddOptions.add("PURPUR_STAIRS");
        ddOptions.add("PURPUR_DOUBLE_SLAB");
        ddOptions.add("PURPUR_SLAB");
        ddOptions.add("END_BRICKS");
        ddOptions.add("BEETROOTS");
        ddOptions.add("GRASS_PATH");
        ddOptions.add("END_GATEWAY");
        ddOptions.add("REPEATING_COMMAND_BLOCK");
        ddOptions.add("CHAIN_COMMAND_BLOCK");
        ddOptions.add("FROSTED_ICE");
        ddOptions.add("MAGMA");
        ddOptions.add("NETHER_WART_BLOCK");
        ddOptions.add("RED_NETHER_BRICK");
        ddOptions.add("BONE_BLOCK");
        ddOptions.add("STRUCTURE_VOID");
        ddOptions.add("OBSERVER");
        ddOptions.add("WHITE_SHULKER_BOX");
        ddOptions.add("ORANGE_SHULKER_BOX");
        ddOptions.add("MAGENTA_SHULKER_BOX");
        ddOptions.add("LIGHT_BLUE_SHULKER_BOX");
        ddOptions.add("YELLOW_SHULKER_BOX");
        ddOptions.add("LIME_SHULKER_BOX");
        ddOptions.add("PINK_SHULKER_BOX");
        ddOptions.add("GRAY_SHULKER_BOX");
        ddOptions.add("SILVER_SHULKER_BOX");
        ddOptions.add("CYAN_SHULKER_BOX");
        ddOptions.add("PURPLE_SHULKER_BOX");
        ddOptions.add("BLUE_SHULKER_BOX");
        ddOptions.add("BROWN_SHULKER_BOX");
        ddOptions.add("GREEN_SHULKER_BOX");
        ddOptions.add("RED_SHULKER_BOX");
        ddOptions.add("BLACK_SHULKER_BOX");
        ddOptions.add("WHITE_GLAZED_TERRACOTTA");
        ddOptions.add("ORANGE_GLAZED_TERRACOTTA");
        ddOptions.add("MAGENTA_GLAZED_TERRACOTTA");
        ddOptions.add("LIGHT_BLUE_GLAZED_TERRACOTTA");
        ddOptions.add("YELLOW_GLAZED_TERRACOTTA");
        ddOptions.add("LIME_GLAZED_TERRACOTTA");
        ddOptions.add("PINK_GLAZED_TERRACOTTA");
        ddOptions.add("GRAY_GLAZED_TERRACOTTA");
        ddOptions.add("SILVER_GLAZED_TERRACOTTA");
        ddOptions.add("CYAN_GLAZED_TERRACOTTA");
        ddOptions.add("PURPLE_GLAZED_TERRACOTTA");
        ddOptions.add("BLUE_GLAZED_TERRACOTTA");
        ddOptions.add("BROWN_GLAZED_TERRACOTTA");
        ddOptions.add("GREEN_GLAZED_TERRACOTTA");
        ddOptions.add("RED_GLAZED_TERRACOTTA");
        ddOptions.add("BLACK_GLAZED_TERRACOTTA");
        ddOptions.add("CONCRETE");
        ddOptions.add("CONCRETE_POWDER");
        ddOptions.add("STRUCTURE_BLOCK");
    }

    @Override
    public Object runCodeObject(DragableBlock dragableBlock, Object event) {
        switch (dragableBlock.dropDowns.getSelected()) {
            case "AIR": return Blocks.AIR;
            case "STONE": return Blocks.STONE;
            case "GRASS": return Blocks.GRASS;
            case "DIRT": return Blocks.DIRT;
            case "COBBLESTONE": return Blocks.COBBLESTONE;
            case "PLANKS": return Blocks.PLANKS;
            case "SAPLING": return Blocks.SAPLING;
            case "BEDROCK": return Blocks.BEDROCK;
            case "FLOWING_WATER": return Blocks.FLOWING_WATER;
            case "WATER": return Blocks.WATER;
            case "FLOWING_LAVA": return Blocks.FLOWING_LAVA;
            case "LAVA": return Blocks.LAVA;
            case "SAND": return Blocks.SAND;
            case "GRAVEL": return Blocks.GRAVEL;
            case "GOLD_ORE": return Blocks.GOLD_ORE;
            case "IRON_ORE": return Blocks.IRON_ORE;
            case "COAL_ORE": return Blocks.COAL_ORE;
            case "LOG": return Blocks.LOG;
            case "LOG2": return Blocks.LOG2;
            case "LEAVES": return Blocks.LEAVES;
            case "LEAVES2": return Blocks.LEAVES2;
            case "SPONGE": return Blocks.SPONGE;
            case "GLASS": return Blocks.GLASS;
            case "LAPIS_ORE": return Blocks.LAPIS_ORE;
            case "LAPIS_BLOCK": return Blocks.LAPIS_BLOCK;
            case "DISPENSER": return Blocks.DISPENSER;
            case "SANDSTONE": return Blocks.SANDSTONE;
            case "NOTEBLOCK": return Blocks.NOTEBLOCK;
            case "BED": return Blocks.BED;
            case "GOLDEN_RAIL": return Blocks.GOLDEN_RAIL;
            case "DETECTOR_RAIL": return Blocks.DETECTOR_RAIL;
            case "STICKY_PISTON": return Blocks.STICKY_PISTON;
            case "WEB": return Blocks.WEB;
            case "TALLGRASS": return Blocks.TALLGRASS;
            case "DEADBUSH": return Blocks.DEADBUSH;
            case "PISTON": return Blocks.PISTON;
            case "PISTON_HEAD": return Blocks.PISTON_HEAD;
            case "WOOL": return Blocks.WOOL;
            case "PISTON_EXTENSION": return Blocks.PISTON_EXTENSION;
            case "YELLOW_FLOWER": return Blocks.YELLOW_FLOWER;
            case "RED_FLOWER": return Blocks.RED_FLOWER;
            case "BROWN_MUSHROOM": return Blocks.BROWN_MUSHROOM;
            case "RED_MUSHROOM": return Blocks.RED_MUSHROOM;
            case "GOLD_BLOCK": return Blocks.GOLD_BLOCK;
            case "IRON_BLOCK": return Blocks.IRON_BLOCK;
            case "DOUBLE_STONE_SLAB": return Blocks.DOUBLE_STONE_SLAB;
            case "STONE_SLAB": return Blocks.STONE_SLAB;
            case "BRICK_BLOCK": return Blocks.BRICK_BLOCK;
            case "TNT": return Blocks.TNT;
            case "BOOKSHELF": return Blocks.BOOKSHELF;
            case "MOSSY_COBBLESTONE": return Blocks.MOSSY_COBBLESTONE;
            case "OBSIDIAN": return Blocks.OBSIDIAN;
            case "TORCH": return Blocks.TORCH;
            case "FIRE": return Blocks.FIRE;
            case "MOB_SPAWNER": return Blocks.MOB_SPAWNER;
            case "OAK_STAIRS": return Blocks.OAK_STAIRS;
            case "CHEST": return Blocks.CHEST;
            case "REDSTONE_WIRE": return Blocks.REDSTONE_WIRE;
            case "DIAMOND_ORE": return Blocks.DIAMOND_ORE;
            case "DIAMOND_BLOCK": return Blocks.DIAMOND_BLOCK;
            case "CRAFTING_TABLE": return Blocks.CRAFTING_TABLE;
            case "WHEAT": return Blocks.WHEAT;
            case "FARMLAND": return Blocks.FARMLAND;
            case "FURNACE": return Blocks.FURNACE;
            case "LIT_FURNACE": return Blocks.LIT_FURNACE;
            case "STANDING_SIGN": return Blocks.STANDING_SIGN;
            case "OAK_DOOR": return Blocks.OAK_DOOR;
            case "SPRUCE_DOOR": return Blocks.SPRUCE_DOOR;
            case "BIRCH_DOOR": return Blocks.BIRCH_DOOR;
            case "JUNGLE_DOOR": return Blocks.JUNGLE_DOOR;
            case "ACACIA_DOOR": return Blocks.ACACIA_DOOR;
            case "DARK_OAK_DOOR": return Blocks.DARK_OAK_DOOR;
            case "LADDER": return Blocks.LADDER;
            case "RAIL": return Blocks.RAIL;
            case "STONE_STAIRS": return Blocks.STONE_STAIRS;
            case "WALL_SIGN": return Blocks.WALL_SIGN;
            case "LEVER": return Blocks.LEVER;
            case "STONE_PRESSURE_PLATE": return Blocks.STONE_PRESSURE_PLATE;
            case "IRON_DOOR": return Blocks.IRON_DOOR;
            case "WOODEN_PRESSURE_PLATE": return Blocks.WOODEN_PRESSURE_PLATE;
            case "REDSTONE_ORE": return Blocks.REDSTONE_ORE;
            case "LIT_REDSTONE_ORE": return Blocks.LIT_REDSTONE_ORE;
            case "UNLIT_REDSTONE_TORCH": return Blocks.UNLIT_REDSTONE_TORCH;
            case "REDSTONE_TORCH": return Blocks.REDSTONE_TORCH;
            case "STONE_BUTTON": return Blocks.STONE_BUTTON;
            case "SNOW_LAYER": return Blocks.SNOW_LAYER;
            case "ICE": return Blocks.ICE;
            case "SNOW": return Blocks.SNOW;
            case "CACTUS": return Blocks.CACTUS;
            case "CLAY": return Blocks.CLAY;
            case "REEDS": return Blocks.REEDS;
            case "JUKEBOX": return Blocks.JUKEBOX;
            case "OAK_FENCE": return Blocks.OAK_FENCE;
            case "SPRUCE_FENCE": return Blocks.SPRUCE_FENCE;
            case "BIRCH_FENCE": return Blocks.BIRCH_FENCE;
            case "JUNGLE_FENCE": return Blocks.JUNGLE_FENCE;
            case "DARK_OAK_FENCE": return Blocks.DARK_OAK_FENCE;
            case "ACACIA_FENCE": return Blocks.ACACIA_FENCE;
            case "PUMPKIN": return Blocks.PUMPKIN;
            case "NETHERRACK": return Blocks.NETHERRACK;
            case "SOUL_SAND": return Blocks.SOUL_SAND;
            case "GLOWSTONE": return Blocks.GLOWSTONE;
            case "PORTAL": return Blocks.PORTAL;
            case "LIT_PUMPKIN": return Blocks.LIT_PUMPKIN;
            case "CAKE": return Blocks.CAKE;
            case "UNPOWERED_REPEATER": return Blocks.UNPOWERED_REPEATER;
            case "POWERED_REPEATER": return Blocks.POWERED_REPEATER;
            case "TRAPDOOR": return Blocks.TRAPDOOR;
            case "MONSTER_EGG": return Blocks.MONSTER_EGG;
            case "STONEBRICK": return Blocks.STONEBRICK;
            case "BROWN_MUSHROOM_BLOCK": return Blocks.BROWN_MUSHROOM_BLOCK;
            case "RED_MUSHROOM_BLOCK": return Blocks.RED_MUSHROOM_BLOCK;
            case "IRON_BARS": return Blocks.IRON_BARS;
            case "GLASS_PANE": return Blocks.GLASS_PANE;
            case "MELON_BLOCK": return Blocks.MELON_BLOCK;
            case "PUMPKIN_STEM": return Blocks.PUMPKIN_STEM;
            case "MELON_STEM": return Blocks.MELON_STEM;
            case "VINE": return Blocks.VINE;
            case "OAK_FENCE_GATE": return Blocks.OAK_FENCE_GATE;
            case "SPRUCE_FENCE_GATE": return Blocks.SPRUCE_FENCE_GATE;
            case "BIRCH_FENCE_GATE": return Blocks.BIRCH_FENCE_GATE;
            case "JUNGLE_FENCE_GATE": return Blocks.JUNGLE_FENCE_GATE;
            case "DARK_OAK_FENCE_GATE": return Blocks.DARK_OAK_FENCE_GATE;
            case "ACACIA_FENCE_GATE": return Blocks.ACACIA_FENCE_GATE;
            case "BRICK_STAIRS": return Blocks.BRICK_STAIRS;
            case "STONE_BRICK_STAIRS": return Blocks.STONE_BRICK_STAIRS;
            case "MYCELIUM": return Blocks.MYCELIUM;
            case "WATERLILY": return Blocks.WATERLILY;
            case "NETHER_BRICK": return Blocks.NETHER_BRICK;
            case "NETHER_BRICK_FENCE": return Blocks.NETHER_BRICK_FENCE;
            case "NETHER_BRICK_STAIRS": return Blocks.NETHER_BRICK_STAIRS;
            case "NETHER_WART": return Blocks.NETHER_WART;
            case "ENCHANTING_TABLE": return Blocks.ENCHANTING_TABLE;
            case "BREWING_STAND": return Blocks.BREWING_STAND;
            case "CAULDRON": return Blocks.CAULDRON;
            case "END_PORTAL": return Blocks.END_PORTAL;
            case "END_PORTAL_FRAME": return Blocks.END_PORTAL_FRAME;
            case "END_STONE": return Blocks.END_STONE;
            case "DRAGON_EGG": return Blocks.DRAGON_EGG;
            case "REDSTONE_LAMP": return Blocks.REDSTONE_LAMP;
            case "LIT_REDSTONE_LAMP": return Blocks.LIT_REDSTONE_LAMP;
            case "DOUBLE_WOODEN_SLAB": return Blocks.DOUBLE_WOODEN_SLAB;
            case "WOODEN_SLAB": return Blocks.WOODEN_SLAB;
            case "COCOA": return Blocks.COCOA;
            case "SANDSTONE_STAIRS": return Blocks.SANDSTONE_STAIRS;
            case "EMERALD_ORE": return Blocks.EMERALD_ORE;
            case "ENDER_CHEST": return Blocks.ENDER_CHEST;
            case "TRIPWIRE_HOOK": return Blocks.TRIPWIRE_HOOK;
            case "TRIPWIRE": return Blocks.TRIPWIRE;
            case "EMERALD_BLOCK": return Blocks.EMERALD_BLOCK;
            case "SPRUCE_STAIRS": return Blocks.SPRUCE_STAIRS;
            case "BIRCH_STAIRS": return Blocks.BIRCH_STAIRS;
            case "JUNGLE_STAIRS": return Blocks.JUNGLE_STAIRS;
            case "COMMAND_BLOCK": return Blocks.COMMAND_BLOCK;
            case "BEACON": return Blocks.BEACON;
            case "COBBLESTONE_WALL": return Blocks.COBBLESTONE_WALL;
            case "FLOWER_POT": return Blocks.FLOWER_POT;
            case "CARROTS": return Blocks.CARROTS;
            case "POTATOES": return Blocks.POTATOES;
            case "WOODEN_BUTTON": return Blocks.WOODEN_BUTTON;
            case "SKULL": return Blocks.SKULL;
            case "ANVIL": return Blocks.ANVIL;
            case "TRAPPED_CHEST": return Blocks.TRAPPED_CHEST;
            case "LIGHT_WEIGHTED_PRESSURE_PLATE": return Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE;
            case "HEAVY_WEIGHTED_PRESSURE_PLATE": return Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE;
            case "UNPOWERED_COMPARATOR": return Blocks.UNPOWERED_COMPARATOR;
            case "POWERED_COMPARATOR": return Blocks.POWERED_COMPARATOR;
            case "DAYLIGHT_DETECTOR": return Blocks.DAYLIGHT_DETECTOR;
            case "DAYLIGHT_DETECTOR_INVERTED": return Blocks.DAYLIGHT_DETECTOR_INVERTED;
            case "REDSTONE_BLOCK": return Blocks.REDSTONE_BLOCK;
            case "QUARTZ_ORE": return Blocks.QUARTZ_ORE;
            case "HOPPER": return Blocks.HOPPER;
            case "QUARTZ_BLOCK": return Blocks.QUARTZ_BLOCK;
            case "QUARTZ_STAIRS": return Blocks.QUARTZ_STAIRS;
            case "ACTIVATOR_RAIL": return Blocks.ACTIVATOR_RAIL;
            case "DROPPER": return Blocks.DROPPER;
            case "STAINED_HARDENED_CLAY": return Blocks.STAINED_HARDENED_CLAY;
            case "BARRIER": return Blocks.BARRIER;
            case "IRON_TRAPDOOR": return Blocks.IRON_TRAPDOOR;
            case "HAY_BLOCK": return Blocks.HAY_BLOCK;
            case "CARPET": return Blocks.CARPET;
            case "HARDENED_CLAY": return Blocks.HARDENED_CLAY;
            case "COAL_BLOCK": return Blocks.COAL_BLOCK;
            case "PACKED_ICE": return Blocks.PACKED_ICE;
            case "ACACIA_STAIRS": return Blocks.ACACIA_STAIRS;
            case "DARK_OAK_STAIRS": return Blocks.DARK_OAK_STAIRS;
            case "SLIME_BLOCK": return Blocks.SLIME_BLOCK;
            case "DOUBLE_PLANT": return Blocks.DOUBLE_PLANT;
            case "STAINED_GLASS": return Blocks.STAINED_GLASS;
            case "STAINED_GLASS_PANE": return Blocks.STAINED_GLASS_PANE;
            case "PRISMARINE": return Blocks.PRISMARINE;
            case "SEA_LANTERN": return Blocks.SEA_LANTERN;
            case "STANDING_BANNER": return Blocks.STANDING_BANNER;
            case "WALL_BANNER": return Blocks.WALL_BANNER;
            case "RED_SANDSTONE": return Blocks.RED_SANDSTONE;
            case "RED_SANDSTONE_STAIRS": return Blocks.RED_SANDSTONE_STAIRS;
            case "DOUBLE_STONE_SLAB2": return Blocks.DOUBLE_STONE_SLAB2;
            case "STONE_SLAB2": return Blocks.STONE_SLAB2;
            case "END_ROD": return Blocks.END_ROD;
            case "CHORUS_PLANT": return Blocks.CHORUS_PLANT;
            case "CHORUS_FLOWER": return Blocks.CHORUS_FLOWER;
            case "PURPUR_BLOCK": return Blocks.PURPUR_BLOCK;
            case "PURPUR_PILLAR": return Blocks.PURPUR_PILLAR;
            case "PURPUR_STAIRS": return Blocks.PURPUR_STAIRS;
            case "PURPUR_DOUBLE_SLAB": return Blocks.PURPUR_DOUBLE_SLAB;
            case "PURPUR_SLAB": return Blocks.PURPUR_SLAB;
            case "END_BRICKS": return Blocks.END_BRICKS;
            case "BEETROOTS": return Blocks.BEETROOTS;
            case "GRASS_PATH": return Blocks.GRASS_PATH;
            case "END_GATEWAY": return Blocks.END_GATEWAY;
            case "REPEATING_COMMAND_BLOCK": return Blocks.REPEATING_COMMAND_BLOCK;
            case "CHAIN_COMMAND_BLOCK": return Blocks.CHAIN_COMMAND_BLOCK;
            case "FROSTED_ICE": return Blocks.FROSTED_ICE;
            case "MAGMA": return Blocks.MAGMA;
            case "NETHER_WART_BLOCK": return Blocks.NETHER_WART_BLOCK;
            case "RED_NETHER_BRICK": return Blocks.RED_NETHER_BRICK;
            case "BONE_BLOCK": return Blocks.BONE_BLOCK;
            case "STRUCTURE_VOID": return Blocks.STRUCTURE_VOID;
            case "OBSERVER": return Blocks.OBSERVER;
            case "WHITE_SHULKER_BOX": return Blocks.WHITE_SHULKER_BOX;
            case "ORANGE_SHULKER_BOX": return Blocks.ORANGE_SHULKER_BOX;
            case "MAGENTA_SHULKER_BOX": return Blocks.MAGENTA_SHULKER_BOX;
            case "LIGHT_BLUE_SHULKER_BOX": return Blocks.LIGHT_BLUE_SHULKER_BOX;
            case "YELLOW_SHULKER_BOX": return Blocks.YELLOW_SHULKER_BOX;
            case "LIME_SHULKER_BOX": return Blocks.LIME_SHULKER_BOX;
            case "PINK_SHULKER_BOX": return Blocks.PINK_SHULKER_BOX;
            case "GRAY_SHULKER_BOX": return Blocks.GRAY_SHULKER_BOX;
            case "SILVER_SHULKER_BOX": return Blocks.SILVER_SHULKER_BOX;
            case "CYAN_SHULKER_BOX": return Blocks.CYAN_SHULKER_BOX;
            case "PURPLE_SHULKER_BOX": return Blocks.PURPLE_SHULKER_BOX;
            case "BLUE_SHULKER_BOX": return Blocks.BLUE_SHULKER_BOX;
            case "BROWN_SHULKER_BOX": return Blocks.BROWN_SHULKER_BOX;
            case "GREEN_SHULKER_BOX": return Blocks.GREEN_SHULKER_BOX;
            case "RED_SHULKER_BOX": return Blocks.RED_SHULKER_BOX;
            case "BLACK_SHULKER_BOX": return Blocks.BLACK_SHULKER_BOX;
            case "WHITE_GLAZED_TERRACOTTA": return Blocks.WHITE_GLAZED_TERRACOTTA;
            case "ORANGE_GLAZED_TERRACOTTA": return Blocks.ORANGE_GLAZED_TERRACOTTA;
            case "MAGENTA_GLAZED_TERRACOTTA": return Blocks.MAGENTA_GLAZED_TERRACOTTA;
            case "LIGHT_BLUE_GLAZED_TERRACOTTA": return Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA;
            case "YELLOW_GLAZED_TERRACOTTA": return Blocks.YELLOW_GLAZED_TERRACOTTA;
            case "LIME_GLAZED_TERRACOTTA": return Blocks.LIME_GLAZED_TERRACOTTA;
            case "PINK_GLAZED_TERRACOTTA": return Blocks.PINK_GLAZED_TERRACOTTA;
            case "GRAY_GLAZED_TERRACOTTA": return Blocks.GRAY_GLAZED_TERRACOTTA;
            case "SILVER_GLAZED_TERRACOTTA": return Blocks.SILVER_GLAZED_TERRACOTTA;
            case "CYAN_GLAZED_TERRACOTTA": return Blocks.CYAN_GLAZED_TERRACOTTA;
            case "PURPLE_GLAZED_TERRACOTTA": return Blocks.PURPLE_GLAZED_TERRACOTTA;
            case "BLUE_GLAZED_TERRACOTTA": return Blocks.BLUE_GLAZED_TERRACOTTA;
            case "BROWN_GLAZED_TERRACOTTA": return Blocks.BROWN_GLAZED_TERRACOTTA;
            case "GREEN_GLAZED_TERRACOTTA": return Blocks.GREEN_GLAZED_TERRACOTTA;
            case "RED_GLAZED_TERRACOTTA": return Blocks.RED_GLAZED_TERRACOTTA;
            case "BLACK_GLAZED_TERRACOTTA": return Blocks.BLACK_GLAZED_TERRACOTTA;
            case "CONCRETE": return Blocks.CONCRETE;
            case "CONCRETE_POWDER": return Blocks.CONCRETE_POWDER;
            case "STRUCTURE_BLOCK": return Blocks.STRUCTURE_BLOCK;
        }
        return false;

    }

}
