name: Java CI with Gradle.

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Set up JDK 8.
        uses: actions/setup-java@v2

        with:
          java-version: 8
          distribution: adopt-openj9
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Grant execute permission for gradlew.
        run: chmod +x gradlew

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/libs/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`.
          retention-days: 30 # The retention period must be between 1 and 90 inclusive.
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt-OpenJ9_jdk/8.0.312-7/x64
          GRADLE_BUILD_ACTION_CACHE_RESTORED: true  
